# .travis.yml
language: go
go:
    - 1.11.4
install: true
sudo: required
go:
  - tip
services:
  - docker
before_install:
  - go get github.com/mattn/goveralls
script:
  - goveralls -v -service=travis-ci
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux